# Generated by Django 5.0.7 on 2024-08-16 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Imported Product', 'Imported Product'), ('Locally Manufactured Product', 'Locally Manufactured Product')], max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='GeneralCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FDA/GSA Standard Test', 'FDA/GSA Standard Test'), ('Custom Test', 'Custom Test')], max_length=100)),
            ],
            options={
                'verbose_name_plural': 'General Categories',
            },
        ),
        migrations.CreateModel(
            name='PricingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Regular', 'Regular'), ('Deluxe', 'Deluxe'), ('Premium', 'Premium'), ('Express', 'Express')], max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Pricing Options',
            },
        ),
        migrations.CreateModel(
            name='SampleDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_method', models.CharField(choices=[('Personal Delivery', 'Personal Delivery'), ('Courier Service', 'Courier Service')], max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Sample Delivery Methods',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.generalcategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TestPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.category')),
                ('pricing_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.pricingoption')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.test')),
            ],
            options={
                'verbose_name_plural': 'Test Prices',
                'unique_together': {('test', 'category', 'pricing_option')},
            },
        ),
        migrations.CreateModel(
            name='TestRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.CharField(blank=True, editable=False, max_length=12, unique=True)),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('delivery_status', models.CharField(choices=[('Pending', 'Pending'), ('Submitted', 'Submitted'), ('Completed', 'Completed')], default='Pending', max_length=100)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=10)),
                ('delivery_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.sampledelivery', verbose_name='Delivery Method')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.testprice')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.test')),
                ('test_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.category', verbose_name='Test Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Test Requests',
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
