# Generated by Django 5.0.7 on 2024-08-16 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_test_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrequest',
            name='price',
        ),
        migrations.AddField(
            model_name='testrequest',
            name='price_option',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.pricingoption'),
            preserve_default=False,
        ),
    ]
