# Generated by Django 5.0.7 on 2024-08-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_testrequest_price_testrequest_price_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrequest',
            name='test_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
