# Generated by Django 5.0.7 on 2024-08-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_testrequest_test_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='price_range',
            field=models.CharField(default='Unavailable', max_length=50),
        ),
    ]
