# Generated by Django 5.0.7 on 2024-08-31 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_test_details_test_price_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrequest',
            name='delivery_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Submitted', 'Submitted'), ('Confirmed', 'Confirmed'), ('Dispatched to Lab', 'Dispatched to Lab'), ('Completed', 'Completed')], default='Pending', max_length=100),
        ),
    ]
